Repository COS301-SE-2022/Map-out-game-reserves-using-aerial-photographs, pull requests merged in 2022-09, with the labels that each got.

#262 ✅ Testing for titles & testing fix in park dialog
  amplify/backend/storage/s3storage/cli-inputs.json
  src/app/components/account/account.component.spec.ts
  src/app/components/account/account.component.ts
  src/app/components/account/email-dialog/email-dialog.component.spec.ts
  src/app/components/dashboard/dashboard.component.spec.ts
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/file-upload/file-upload.component.spec.ts
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/file-upload/parks-dialog/parks-dialog.component.spec.ts
  src/app/components/login/login.component.spec.ts
  src/app/components/login/login.component.ts
  src/app/components/register/register.component.spec.ts
  src/app/components/register/register.component.ts
Labels: scope:ui, type:test, priority:high

#263 🐛 CICD: Fixed Codecov
  karma.conf.js
Labels: scope:cicd, type:fix, priority:medium

#264 Update README.md
  README.md
Labels: scope:repository, type:documentation, priority:medium

#265 🚧(client/backend): Integrating local WebODM server
  .gitignore
  LocalWebODMServer/package-lock.json
  LocalWebODMServer/package.json
  LocalWebODMServer/tsconfig.json
  LocalWebODMServer/webODM-server.ts
  amplify/backend/storage/S3Storage/cli-inputs.json
  package-lock.json
  package.json
  scripts/setenv.ts
  src/app/api/controller/controller.service.ts
  src/app/app.component.ts
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/image-catalogue/image-catalogue.component.html
  src/app/components/image-catalogue/image-catalogue.component.ts
  src/app/components/image-catalogue/image-dialog/image-dialog.component.html
  src/environments/environment.ts
  tsconfig.json
Labels: scope:api, scope:client, scope:repository, type:feature, priority:medium

#268 🧪(testing): Adding env variable generation to tests.yml workflow
  .github/workflows/tests.yml
  LocalWebODMServer/webODM-server.ts
  package.json
  scripts/setenv.js
  src/app/components/image-catalogue/image-catalogue.component.ts
  src/app/components/image-catalogue/image-dialog/image-dialog.component.html
  src/app/components/image-catalogue/image-dialog/image-dialog.component.ts
  src/app/components/map/map.component.html
  src/app/components/map/map.component.spec.ts
  src/app/components/map/map.component.ts
  src/app/components/map/map.module.ts
  src/app/components/map/safe.pipe.spec.ts
  src/app/components/map/safe.pipe.ts
Labels: type:bug, scope:cicd, scope:client, type:feature, type:fix, priority:high

#269 💄(ui): add mapbox to dashboard
  amplify/.config/project-config.json
  amplify/README.md
  amplify/backend/storage/s3storage/cli-inputs.json
  package-lock.json
  package.json
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.module.ts
  src/app/components/dashboard/mapbox/mapbox.component.html
  src/app/components/dashboard/mapbox/mapbox.component.scss
  src/app/components/dashboard/mapbox/mapbox.component.spec.ts
  src/app/components/dashboard/mapbox/mapbox.component.ts
  src/app/components/dashboard/mapbox/mapbox.model.ts
  src/graphql/schema.json
  src/index.html
Labels: scope:ui, type:feature, priority:high

#271 💄: Adding a starting off spinner to all the pages
  src/app/app.module.ts
  src/app/components/account/account.component.html
  src/app/components/account/account.component.ts
  src/app/components/account/account.module.ts
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/dashboard/dashboard.module.ts
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/file-upload/file-upload.module.ts
  src/app/components/image-catalogue/image-catalogue.component.html
  src/app/components/image-catalogue/image-catalogue.component.ts
  src/app/components/image-catalogue/image-catalogue.module.ts
  src/app/components/login/login.component.html
  src/app/components/login/login.component.scss
  src/app/components/login/login.component.ts
  src/app/components/login/login.module.ts
  src/app/components/register/register.component.html
  src/app/components/register/register.component.ts
  src/app/components/register/register.module.ts
  src/app/components/shared/navbar/navbar.component.ts
  src/app/components/shared/spinner/spinner.component.html
  src/app/components/shared/spinner/spinner.component.scss
  src/app/components/shared/spinner/spinner.component.spec.ts
  src/app/components/shared/spinner/spinner.component.ts
  src/app/components/shared/spinner/spinner.module.ts
Labels: scope:ui, type:feature, priority:high

#270 🐛(client): Fixing image catalogue dialog buttons bug
  .github/workflows/tests.yml
  LocalWebODMServer/webODM-server.ts
  angular.json
  codecov.yml
  karma.conf.js
  scripts/setenv.js
  src/app/api/controller/controller.service.ts
  src/app/auth/auth.guard.spec.ts
  src/app/auth/auth.guard.ts
  src/app/auth/aws-amplify-wrapper.spec.ts
  src/app/auth/aws-amplify-wrapper.ts
  src/app/components/account/account.component.scss
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/file-upload/parks-dialog/parks-dialog.component.spec.ts
  src/app/components/image-catalogue/image-dialog/image-dialog.component.html
  src/app/components/image-catalogue/image-dialog/image-dialog.component.ts
  src/app/components/map/map.component.ts
  src/graphql/schema.json
  src/index.html
Labels: scope:api, scope:client, type:feature, type:test, type:fix, priority:low

#273 💄 Adding in spinners to the map catalogue
  src/app/components/account/account.component.ts
  src/app/components/image-catalogue/image-catalogue.component.html
  src/app/components/image-catalogue/image-catalogue.component.scss
  src/app/components/image-catalogue/image-catalogue.component.ts
  src/app/components/image-catalogue/image-catalogue.module.ts
  src/app/components/image-catalogue/image-dialog/image-dialog.component.html
  src/app/components/image-catalogue/image-dialog/image-dialog.component.scss
  src/app/components/image-catalogue/image-dialog/image-dialog.component.ts
  src/app/components/shared/spinner/spinner.component.scss
Labels: scope:ui, type:feature, priority:medium

#272 🧪(webpack): Trying to generate env variables on GitHub
  angular.json
  custom-webpack.config.ts
  package-lock.json
  package.json
  src/app/components/file-upload/file-upload.component.ts
  src/environments/environment.prod.ts
Labels: scope:cicd, type:test, priority:low

#276 Update README.md
  README.md
Labels: scope:repository, type:fix, priority:medium

#274 📦(package.json): Removing package which is preventing deployment
  README.md
  amplify/backend/backend-config.json
  amplify/backend/hosting/amplifyhosting/amplifyhosting-template.json
  amplify/team-provider-info.json
  custom-webpack.config.ts
  package-lock.json
  package.json
  scripts/setenv.js
  src/app/components/file-upload/file-upload.component.spec.ts
  src/app/components/file-upload/file-upload.component.ts
Labels: scope:cicd, scope:client, type:test, type:fix, priority:high

#277 💄 File upload page update
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.component.scss
  src/app/components/file-upload/file-upload.component.spec.ts
  src/app/components/file-upload/file-upload.component.ts
Labels: scope:ui, type:fix, priority:medium

#281 Adding functionality for the user to be able to open an image in a ne…
  src/app/components/image-catalogue/image-dialog/image-dialog.component.html
  src/app/components/image-catalogue/image-dialog/image-dialog.component.ts
Labels: scope:ui, type:feature, priority:low

#279 💄 (ui): add styling for error handling
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.component.scss
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/dashboard/dashboard.module.ts
  src/app/components/image-catalogue/image-dialog/image-dialog.component.html
  src/app/components/image-catalogue/image-dialog/image-dialog.component.scss
  src/app/components/image-catalogue/image-dialog/image-dialog.component.ts
Labels: scope:ui, type:feature, priority:medium

#283 ✨(api): Added Auth to API
  amplify/backend/api/aerialmapping/cli-inputs.json
  amplify/backend/api/aerialmapping/parameters.json
  amplify/backend/api/aerialmapping/schema.graphql
  amplify/backend/backend-config.json
  amplify/backend/types/amplify-dependent-resources-ref.d.ts
  src/app/API.service.ts
  src/app/api/controller/controller.service.ts
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/file-upload/file-upload.component.scss
  src/app/components/image-catalogue/image-catalogue.component.ts
  src/graphql/queries.graphql
  src/graphql/schema.json
  src/graphql/subscriptions.graphql
  src/main.ts
Labels: scope:api, scope:client, type:feature, type:fix, priority:medium

#282 ✨Adding backend functionality to dismiss messages and delete maps
  amplify/backend/api/aerialmapping/schema.graphql
  amplify/backend/storage/s3storage/cli-inputs.json
  amplify/team-provider-info.json
  src/app/API.service.ts
  src/app/api/controller/controller.service.ts
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/image-catalogue/image-dialog/image-dialog.component.html
  src/app/components/image-catalogue/image-dialog/image-dialog.component.spec.ts
  src/app/components/image-catalogue/image-dialog/image-dialog.component.ts
  src/graphql/mutations.graphql
  src/graphql/queries.graphql
  src/graphql/schema.json
  src/graphql/subscriptions.graphql
Labels: scope:api, type:feature, priority:high

#285 ✅ Tests: Added tests to the dialog components
  src/app/components/account/email-dialog/email-dialog.component.spec.ts
  src/app/components/account/name-dialog/name-dialog.component.spec.ts
  src/app/components/account/password-dialog/password-dialog.component.spec.ts
  src/app/components/account/password-dialog/password-dialog.component.ts
  src/app/components/account/register-link-dialog/register-link-dialog.component.spec.ts
  src/app/components/file-upload/parks-dialog/parks-dialog.component.spec.ts
  src/app/components/image-catalogue/image-dialog/image-dialog.component.spec.ts
  src/app/components/register/otp-dialog/otp-dialog.component.spec.ts
  src/app/components/register/otp-dialog/otp-dialog.component.ts
Labels: scope:cicd, type:test, priority:medium

#289 ✨ Adding delete error messages and confirm for deleting maps
  src/app/components/dashboard/dashboard.component.html
  src/app/components/image-catalogue/image-dialog/confirm-dialog/confirm-dialog.component.html
  src/app/components/image-catalogue/image-dialog/confirm-dialog/confirm-dialog.component.scss
  src/app/components/image-catalogue/image-dialog/confirm-dialog/confirm-dialog.component.spec.ts
  src/app/components/image-catalogue/image-dialog/confirm-dialog/confirm-dialog.component.ts
  src/app/components/image-catalogue/image-dialog/image-dialog.component.html
  src/app/components/image-catalogue/image-dialog/image-dialog.component.ts
Labels: scope:ui, type:feature, priority:high

#290 Updating the Login page
  src/app/components/login/login.component.html
  src/app/components/login/login.component.scss
  src/app/components/login/login.component.ts
  src/app/components/login/login.module.ts
  src/assets/erpngo-header-full - Copy.jpg
Labels: scope:client, type:fix, priority:medium

#291 Update README.md
  README.md
Labels: scope:repository, type:documentation, priority:low

#292 🐛 : Fixing IP referencing. Bypass image resizing.
  LocalWebODMServer/webODM-server.ts
  package-lock.json
  package.json
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/map/map.component.ts
Labels: type:bug, scope:db, type:fix, priority:high

#293 🐛 Attempt to fix delete maps
  src/app/components/file-upload/file-upload.component.spec.ts
  src/app/components/image-catalogue/image-dialog/image-dialog.component.ts
Labels: type:bug, scope:api, type:feature, priority:high

#295 ✨ (ui): Adding map resolution slider
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.component.scss
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/file-upload/file-upload.module.ts
Labels: scope:ui, type:feature, priority:high

#299 Update of the register page
  src/app/app.component.html
  src/app/components/register/register.component.html
  src/app/components/register/register.component.scss
  src/app/components/register/register.component.ts
  src/app/components/register/register.module.ts
Labels: scope:ui, type:fix, priority:medium

#300 Allowing the user to be able to go back in the app
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/shared/navbar/navbar.component.ts
Labels: scope:ui, type:fix, priority:medium

#301 🎨(code formatting): formatted all code to be prettified
  src/app/API.service.ts
  src/app/api/controller/controller.service.spec.ts
  src/app/api/controller/controller.service.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/account/account.component.html
  src/app/components/account/account.component.ts
  src/app/components/account/email-dialog/email-dialog.component.html
  src/app/components/account/email-dialog/email-dialog.component.ts
  src/app/components/account/name-dialog/name-dialog.component.html
  src/app/components/account/name-dialog/name-dialog.component.ts
  src/app/components/account/password-dialog/password-dialog.component.html
  src/app/components/account/password-dialog/password-dialog.component.ts
  src/app/components/account/register-link-dialog/register-link-dialog.component.html
  src/app/components/account/register-link-dialog/register-link-dialog.component.ts
  src/app/components/dashboard/bar-chart/bar-chart.component.html
  src/app/components/dashboard/bar-chart/bar-chart.component.scss
  src/app/components/dashboard/bar-chart/bar-chart.component.spec.ts
  src/app/components/dashboard/bar-chart/bar-chart.component.ts
  src/app/components/dashboard/bar-chart/bar-chart.model.ts
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/dashboard/dashboard.module.ts
  src/app/components/dashboard/mapbox/mapbox.component.html
  src/app/components/dashboard/mapbox/mapbox.component.spec.ts
  src/app/components/dashboard/mapbox/mapbox.component.ts
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/file-upload/parks-dialog/parks-dialog.component.html
  src/app/components/file-upload/parks-dialog/parks-dialog.component.ts
  src/app/components/image-catalogue/image-catalogue.component.html
  src/app/components/image-catalogue/image-catalogue.component.ts
  src/app/components/image-catalogue/image-dialog/confirm-dialog/confirm-dialog.component.ts
  src/app/components/image-catalogue/image-dialog/image-dialog.component.html
  src/app/components/image-catalogue/image-dialog/image-dialog.component.ts
  src/app/components/login/login.component.html
  src/app/components/login/login.component.ts
  src/app/components/map/map.component.html
  src/app/components/map/map.component.ts
  src/app/components/register/otp-dialog/otp-dialog.component.html
  src/app/components/register/register.component.html
  src/app/components/register/register.component.ts
  src/app/components/shared/footer/footer.component.html
  src/app/components/shared/navbar/navbar.component.html
  src/app/components/shared/spinner/spinner.component.html
Labels: scope:design, type:fix, priority:low

#304 Revert "🎨(code formatting): formatted all code to be prettified"
  src/app/API.service.ts
  src/app/api/controller/controller.service.spec.ts
  src/app/api/controller/controller.service.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/account/account.component.html
  src/app/components/account/account.component.ts
  src/app/components/account/email-dialog/email-dialog.component.html
  src/app/components/account/email-dialog/email-dialog.component.ts
  src/app/components/account/name-dialog/name-dialog.component.html
  src/app/components/account/name-dialog/name-dialog.component.ts
  src/app/components/account/password-dialog/password-dialog.component.html
  src/app/components/account/password-dialog/password-dialog.component.ts
  src/app/components/account/register-link-dialog/register-link-dialog.component.html
  src/app/components/account/register-link-dialog/register-link-dialog.component.ts
  src/app/components/dashboard/bar-chart/bar-chart.component.html
  src/app/components/dashboard/bar-chart/bar-chart.component.scss
  src/app/components/dashboard/bar-chart/bar-chart.component.spec.ts
  src/app/components/dashboard/bar-chart/bar-chart.component.ts
  src/app/components/dashboard/bar-chart/bar-chart.model.ts
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/dashboard/dashboard.module.ts
  src/app/components/dashboard/mapbox/mapbox.component.html
  src/app/components/dashboard/mapbox/mapbox.component.spec.ts
  src/app/components/dashboard/mapbox/mapbox.component.ts
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/file-upload/parks-dialog/parks-dialog.component.html
  src/app/components/file-upload/parks-dialog/parks-dialog.component.ts
  src/app/components/image-catalogue/image-catalogue.component.html
  src/app/components/image-catalogue/image-catalogue.component.ts
  src/app/components/image-catalogue/image-dialog/confirm-dialog/confirm-dialog.component.ts
  src/app/components/image-catalogue/image-dialog/image-dialog.component.html
  src/app/components/image-catalogue/image-dialog/image-dialog.component.ts
  src/app/components/login/login.component.html
  src/app/components/login/login.component.ts
  src/app/components/map/map.component.html
  src/app/components/map/map.component.ts
  src/app/components/register/otp-dialog/otp-dialog.component.html
  src/app/components/register/register.component.html
  src/app/components/register/register.component.ts
  src/app/components/shared/footer/footer.component.html
  src/app/components/shared/navbar/navbar.component.html
  src/app/components/shared/spinner/spinner.component.html
Labels: type:bug, scope:cicd, scope:repository, type:fix, priority:high

#302 ✅(testing): Adding performance quality requirements integration tests
  .github/workflows/tests.yml
  custom-webpack.config.ts
  cypress.config.ts
  cypress/e2e/app.po.ts
  cypress/e2e/spec.cy.ts
  package-lock.json
  package.json
  src/app/auth/auth.guard.spec.ts
  src/app/components/account/account.component.html
  src/app/components/account/account.component.ts
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/image-catalogue/image-catalogue.component.ts
  src/app/components/login/login.component.spec.ts
  src/app/components/login/login.component.ts
  src/graphql/schema.json
Labels: scope:cicd, type:test, priority:high

#303 🚀 Adding TLS layer compatibility for ODM server
  LocalWebODMServer/webODM-server.ts
  src/app/components/map/map.component.html
  src/app/components/map/map.component.scss
  src/app/components/map/map.component.ts
Labels: scope:api, type:fix, priority:high

#305 💄(ui): Updating the register, login, and file upload pages
  src/app/components/account/account.component.scss
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.component.scss
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/login/login.component.html
  src/app/components/login/login.component.scss
  src/app/components/login/login.component.ts
  src/app/components/login/login.module.ts
  src/app/components/register/register.component.html
  src/app/components/register/register.component.scss
  src/app/components/register/register.component.ts
  src/app/components/register/register.module.ts
Labels: scope:ui, type:fix, priority:medium

#306 🚧(client/api): Fixing Register email problem
  amplify/backend/types/amplify-dependent-resources-ref.d.ts
  amplify/team-provider-info.json
  cypress.config.ts
  src/app/api/controller/controller.service.ts
  src/app/auth/auth.guard.spec.ts
  src/app/components/account/account.component.spec.ts
  src/app/components/account/account.component.ts
  src/app/components/map/map.component.html
  src/graphql/schema.json
Labels: scope:api, scope:client, type:test, type:fix, priority:high

#307 🎨 Clean up some files
  .github/workflows/index.yml
  .github/workflows/tests.yml
  src/app/components/dashboard/bar-chart/bar-chart.component.html
  src/app/components/dashboard/bar-chart/bar-chart.component.scss
  src/app/components/dashboard/bar-chart/bar-chart.component.spec.ts
  src/app/components/dashboard/bar-chart/bar-chart.component.ts
  src/app/components/dashboard/bar-chart/bar-chart.model.ts
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.component.scss
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/dashboard/dashboard.module.ts
  src/app/components/shared/navbar/navbar.component.html
  src/app/components/shared/navbar/navbar.component.scss
  src/app/components/shared/navbar/navbar.component.spec.ts
  src/app/components/shared/navbar/navbar.component.ts
  src/app/components/shared/navbar/navbar.module.ts
Labels: scope:cicd, type:refactor, priority:low

#308 ✨ Adding park name to collections
  src/app/components/dashboard/dashboard.component.html
  src/app/components/image-catalogue/image-catalogue.component.html
  src/app/components/image-catalogue/image-catalogue.component.scss
  src/app/components/image-catalogue/image-catalogue.component.ts
Labels: scope:ui, type:feature, priority:high

#309 💄 (UI) Minor UI changes for Potree viewing
  src/app/components/map/map.component.scss
  src/app/components/map/map.component.ts
Labels: scope:client, scope:ui, type:feature, priority:low

#310 🐛(db): fixed sorting and delete for maps
  src/app/components/image-catalogue/image-catalogue.component.html
  src/app/components/image-catalogue/image-catalogue.component.ts
  src/app/components/image-catalogue/image-dialog/image-dialog.component.ts
Labels: type:bug, scope:db, type:fix, priority:medium

#317 Quick update to the description on our login and register component
  src/app/components/login/login.component.html
  src/app/components/register/register.component.html
Labels: scope:ui, type:fix, priority:low

#315 🎨(code formatting): reformatted all .ts files
  src/app/api/controller/controller.service.ts
  src/app/components/account/account.component.ts
  src/app/components/account/email-dialog/email-dialog.component.ts
  src/app/components/account/name-dialog/name-dialog.component.ts
  src/app/components/account/password-dialog/password-dialog.component.ts
  src/app/components/account/register-link-dialog/register-link-dialog.component.ts
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/dashboard/mapbox/mapbox.component.ts
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/file-upload/parks-dialog/parks-dialog.component.ts
  src/app/components/image-catalogue/image-catalogue.component.html
  src/app/components/image-catalogue/image-catalogue.component.ts
  src/app/components/image-catalogue/image-dialog/confirm-dialog/confirm-dialog.component.ts
  src/app/components/image-catalogue/image-dialog/image-dialog.component.ts
  src/app/components/login/login.component.ts
  src/app/components/map/map.component.ts
  src/app/components/map/map.module.ts
  src/app/components/map/safe.pipe.ts
  src/app/components/register/register.component.ts
  src/app/components/shared/footer/footer.component.ts
  src/app/components/shared/spinner/spinner.component.ts
Labels: scope:repository, type:fix, priority:low

#318 Update README.md
  README.md
Labels: scope:repository, type:documentation, priority:high

#319 ✅(testing): Added Login Performance Quality Test
  src/app/components/login/login.component.spec.ts
Labels: scope:cicd, type:test, priority:high

#321 Merging member/DylanP into develop
  .github/workflows/integration.yml
  package-lock.json
  src/app/components/file-upload/file-upload.component.spec.ts
  src/app/components/image-catalogue/image-catalogue.component.spec.ts
Labels: scope:cicd, type:feature, priority:high

#323 Update README.md
  README.md
Labels: scope:repository, type:documentation, priority:high
