Repository COS301-SE-2022/Map-out-game-reserves-using-aerial-photographs, pull requests merged in 2022-05, with the labels that each got.

#7 ✨(ui): Adding Login, Register and routing
  aerial-mapping/angular.json
  aerial-mapping/apps/aerial-mapping/src/app/app-routing.module.ts
  aerial-mapping/apps/aerial-mapping/src/app/app.component.html
  aerial-mapping/apps/aerial-mapping/src/app/app.module.ts
  aerial-mapping/libs/client/dashboard/src/lib/client-dashboard.module.ts
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-routing.module.ts
  aerial-mapping/libs/client/login/.eslintrc.json
  aerial-mapping/libs/client/login/README.md
  aerial-mapping/libs/client/login/jest.config.ts
  aerial-mapping/libs/client/login/project.json
  aerial-mapping/libs/client/login/src/index.ts
  aerial-mapping/libs/client/login/src/lib/client-login.module.spec.ts
  aerial-mapping/libs/client/login/src/lib/client-login.module.ts
  aerial-mapping/libs/client/login/src/lib/login-routing.module.ts
  aerial-mapping/libs/client/login/src/lib/login/login.component.html
  aerial-mapping/libs/client/login/src/lib/login/login.component.scss
  aerial-mapping/libs/client/login/src/lib/login/login.component.spec.ts
  aerial-mapping/libs/client/login/src/lib/login/login.component.ts
  aerial-mapping/libs/client/login/src/test-setup.ts
  aerial-mapping/libs/client/login/tsconfig.json
  aerial-mapping/libs/client/login/tsconfig.lib.json
  aerial-mapping/libs/client/login/tsconfig.spec.json
  aerial-mapping/libs/client/register/.eslintrc.json
  aerial-mapping/libs/client/register/README.md
  aerial-mapping/libs/client/register/jest.config.ts
  aerial-mapping/libs/client/register/project.json
  aerial-mapping/libs/client/register/src/index.ts
  aerial-mapping/libs/client/register/src/lib/client-register.module.spec.ts
  aerial-mapping/libs/client/register/src/lib/client-register.module.ts
  aerial-mapping/libs/client/register/src/lib/register-routing.module.ts
  aerial-mapping/libs/client/register/src/lib/register/register.component.html
  aerial-mapping/libs/client/register/src/lib/register/register.component.scss
  aerial-mapping/libs/client/register/src/lib/register/register.component.spec.ts
  aerial-mapping/libs/client/register/src/lib/register/register.component.ts
  aerial-mapping/libs/client/register/src/test-setup.ts
  aerial-mapping/libs/client/register/tsconfig.json
  aerial-mapping/libs/client/register/tsconfig.lib.json
  aerial-mapping/libs/client/register/tsconfig.spec.json
  aerial-mapping/tsconfig.base.json
Labels: scope:client, scope:ui, type:feature, priority:high

#9 ✨ Added Angular Materials imports
  aerial-mapping/libs/client/register/src/lib/client-register.module.spec.ts
  aerial-mapping/libs/client/register/src/lib/client-register.module.ts
  aerial-mapping/libs/client/register/src/lib/materials/material.module.ts
  aerial-mapping/libs/client/register/src/lib/register/register.component.spec.ts
  aerial-mapping/package.json
  aerial-mapping/yarn.lock
Labels: scope:ui, type:feature, priority:high

#11 Create a global.scss
  aerial-mapping/angular.json
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.html
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.scss
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.ts
  aerial-mapping/libs/client/shared/assets/.eslintrc.json
  aerial-mapping/libs/client/shared/assets/README.md
  aerial-mapping/libs/client/shared/assets/jest.config.ts
  aerial-mapping/libs/client/shared/assets/project.json
  aerial-mapping/libs/client/shared/assets/src/index.ts
  aerial-mapping/libs/client/shared/assets/src/lib/assets.module.ts
  aerial-mapping/libs/client/shared/assets/src/lib/global.scss
  aerial-mapping/libs/client/shared/assets/src/test-setup.ts
  aerial-mapping/libs/client/shared/assets/tsconfig.json
  aerial-mapping/libs/client/shared/assets/tsconfig.lib.json
  aerial-mapping/libs/client/shared/assets/tsconfig.spec.json
  aerial-mapping/tsconfig.base.json
Labels: enhancement, scope:client, type:feature, priority:low

#12 ✨UI for the login page
  aerial-mapping/libs/client/login/src/lib/client-login.module.ts
  aerial-mapping/libs/client/login/src/lib/login/login.component.html
  aerial-mapping/libs/client/login/src/lib/login/login.component.scss
Labels: scope:design, scope:ui, priority:medium

#16 ✨ (ui): Adding File Upload Page
  aerial-mapping/angular.json
  aerial-mapping/apps/aerial-mapping/src/app/app-routing.module.ts
  aerial-mapping/libs/client/file-upload/.eslintrc.json
  aerial-mapping/libs/client/file-upload/README.md
  aerial-mapping/libs/client/file-upload/jest.config.ts
  aerial-mapping/libs/client/file-upload/project.json
  aerial-mapping/libs/client/file-upload/src/index.ts
  aerial-mapping/libs/client/file-upload/src/lib/client-file-upload.module.spec.ts
  aerial-mapping/libs/client/file-upload/src/lib/client-file-upload.module.ts
  aerial-mapping/libs/client/file-upload/src/lib/file-upload-routing.module.ts
  aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.html
  aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.scss
  aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.spec.ts
  aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.ts
  aerial-mapping/libs/client/file-upload/src/test-setup.ts
  aerial-mapping/libs/client/file-upload/tsconfig.json
  aerial-mapping/libs/client/file-upload/tsconfig.lib.json
  aerial-mapping/libs/client/file-upload/tsconfig.spec.json
  aerial-mapping/tsconfig.base.json
Labels: scope:client, scope:ui, type:feature, priority:high

#14 💄UI: Implement Dashboard and Navbar Design
  aerial-mapping/angular.json
  aerial-mapping/apps/aerial-mapping/src/app/app.component.html
  aerial-mapping/apps/aerial-mapping/src/app/app.module.ts
  aerial-mapping/libs/client/dashboard/src/lib/client-dashboard.module.ts
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.html
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.scss
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.ts
  aerial-mapping/libs/client/shared/assets/src/lib/global.scss
  aerial-mapping/libs/client/shared/components/footer/.eslintrc.json
  aerial-mapping/libs/client/shared/components/footer/README.md
  aerial-mapping/libs/client/shared/components/footer/jest.config.ts
  aerial-mapping/libs/client/shared/components/footer/project.json
  aerial-mapping/libs/client/shared/components/footer/src/index.ts
  aerial-mapping/libs/client/shared/components/footer/src/lib/client-shared-components-footer.module.spec.ts
  aerial-mapping/libs/client/shared/components/footer/src/lib/client-shared-components-footer.module.ts
  aerial-mapping/libs/client/shared/components/footer/src/test-setup.ts
  aerial-mapping/libs/client/shared/components/footer/tsconfig.json
  aerial-mapping/libs/client/shared/components/footer/tsconfig.lib.json
  aerial-mapping/libs/client/shared/components/footer/tsconfig.spec.json
  aerial-mapping/libs/client/shared/components/navbar/.eslintrc.json
  aerial-mapping/libs/client/shared/components/navbar/README.md
  aerial-mapping/libs/client/shared/components/navbar/jest.config.ts
  aerial-mapping/libs/client/shared/components/navbar/project.json
  aerial-mapping/libs/client/shared/components/navbar/src/index.ts
  aerial-mapping/libs/client/shared/components/navbar/src/lib/client-shared-components-navbar.module.spec.ts
  aerial-mapping/libs/client/shared/components/navbar/src/lib/client-shared-components-navbar.module.ts
  aerial-mapping/libs/client/shared/components/navbar/src/lib/side-navbar/side-navbar.component.html
  aerial-mapping/libs/client/shared/components/navbar/src/lib/side-navbar/side-navbar.component.scss
  aerial-mapping/libs/client/shared/components/navbar/src/lib/side-navbar/side-navbar.component.spec.ts
  aerial-mapping/libs/client/shared/components/navbar/src/lib/side-navbar/side-navbar.component.ts
  aerial-mapping/libs/client/shared/components/navbar/src/test-setup.ts
  aerial-mapping/libs/client/shared/components/navbar/tsconfig.json
  aerial-mapping/libs/client/shared/components/navbar/tsconfig.lib.json
  aerial-mapping/libs/client/shared/components/navbar/tsconfig.spec.json
  aerial-mapping/tsconfig.base.json
Labels: scope:client, scope:design, type:feature, priority:high

#19 ✨ (ui): Adding File Upload Page
  aerial-mapping/angular.json
  aerial-mapping/apps/aerial-mapping/src/app/app-routing.module.ts
  aerial-mapping/libs/client/file-upload/.eslintrc.json
  aerial-mapping/libs/client/file-upload/README.md
  aerial-mapping/libs/client/file-upload/jest.config.ts
  aerial-mapping/libs/client/file-upload/project.json
  aerial-mapping/libs/client/file-upload/src/index.ts
  aerial-mapping/libs/client/file-upload/src/lib/client-file-upload.module.spec.ts
  aerial-mapping/libs/client/file-upload/src/lib/client-file-upload.module.ts
  aerial-mapping/libs/client/file-upload/src/lib/file-upload-routing.module.ts
  aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.html
  aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.scss
  aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.spec.ts
  aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.ts
  aerial-mapping/libs/client/file-upload/src/test-setup.ts
  aerial-mapping/libs/client/file-upload/tsconfig.json
  aerial-mapping/libs/client/file-upload/tsconfig.lib.json
  aerial-mapping/libs/client/file-upload/tsconfig.spec.json
  aerial-mapping/tsconfig.base.json
Labels: scope:client, scope:ui, type:feature, priority:high

#20 ✨(ui): Basic UI for registration form
  aerial-mapping/apps/aerial-mapping/src/assets/erpngo-header.jpg
  aerial-mapping/libs/client/register/src/lib/client-register.module.spec.ts
  aerial-mapping/libs/client/register/src/lib/client-register.module.ts
  aerial-mapping/libs/client/register/src/lib/erpngo-header.jpg
  aerial-mapping/libs/client/register/src/lib/materials/material.module.ts
  aerial-mapping/libs/client/register/src/lib/register/register.component.html
  aerial-mapping/libs/client/register/src/lib/register/register.component.scss
  aerial-mapping/libs/client/register/src/lib/register/register.component.ts
Labels: scope:ui, type:feature, priority:high

#21 🚧(db): Updated the prisma schema
  aerial-mapping/prisma/schema.prisma
Labels: scope:db, type:feature, priority:high

#22 💄(ui): Added Header image and updated register feature
  aerial-mapping/apps/aerial-mapping/src/assets/erpngo-header-full.jpg
  aerial-mapping/libs/client/register/src/lib/client-register.module.ts
  aerial-mapping/libs/client/register/src/lib/erpngo-header.jpg
  aerial-mapping/libs/client/register/src/lib/register/register.component.html
  aerial-mapping/libs/client/register/src/lib/register/register.component.scss
Labels: scope:ui, type:feature, priority:high

#23 Changes to Log In UI
  aerial-mapping/libs/client/login/src/lib/login/login.component.html
  aerial-mapping/libs/client/login/src/lib/login/login.component.scss
Labels: scope:design, scope:ui, priority:high

#24 🚧(db): Constructing schema.prisma
  aerial-mapping/prisma/migrations/20220510223819_initial_migration/migration.sql
  aerial-mapping/prisma/migrations/migration_lock.toml
  aerial-mapping/prisma/schema.prisma
Labels: scope:db, type:feature, priority:high

#27 🚧(db): Adding to schema.prisma
  aerial-mapping/prisma/schema.prisma
Labels: scope:db, type:feature, priority:high

#32 💄(ui): Finished UI for register
  aerial-mapping/libs/client/register/src/lib/register/register.component.html
  aerial-mapping/libs/client/register/src/lib/register/register.component.scss
Labels: scope:ui, type:feature, priority:high

#33 Added Upload interface and Routing to File Upload page in navbar
  aerial-mapping/apps/aerial-mapping/src/app/app.module.ts
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.scss
  aerial-mapping/libs/client/file-upload/src/lib/client-file-upload.module.ts
  aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.html
  aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.scss
  aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.ts
  aerial-mapping/libs/client/shared/components/navbar/src/lib/side-navbar/side-navbar.component.html
Labels: enhancement, scope:client, scope:db, scope:design, type:feature, priority:medium

#36 💄(ui): Formatting fixes
  aerial-mapping/libs/client/register/src/lib/register/register.component.html
  aerial-mapping/libs/client/register/src/lib/register/register.component.scss
Labels: scope:ui, type:feature, priority:high

#37 💄(ui): Final Login UI
  aerial-mapping/libs/client/login/src/lib/login/login.component.html
  aerial-mapping/libs/client/login/src/lib/login/login.component.scss
Labels: scope:ui, type:feature, priority:high

#28 🎨(db): Updated the format of prisma.schema and added relations
  aerial-mapping/prisma/schema.prisma
Labels: scope:db, type:feature, priority:high

#39 💄 UI: Messages
  aerial-mapping/apps/aerial-mapping/src/assets/ERP_Logo.png
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.html
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.scss
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.ts
  aerial-mapping/libs/client/shared/assets/src/lib/global.scss
  aerial-mapping/libs/client/shared/components/navbar/src/lib/side-navbar/side-navbar.component.scss
Labels: enhancement, scope:client, scope:design, type:feature, priority:high

#41 Minor updates to file upload backend
  aerial-mapping/libs/client/file-upload/src/lib/client-file-upload.module.ts
  aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.html
  aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.scss
  aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.ts
Labels: bug, scope:client, priority:low

#42 Login page: taking out register link and styling fixes
  aerial-mapping/libs/client/login/src/lib/login/login.component.html
  aerial-mapping/libs/client/login/src/lib/login/login.component.scss
Labels: scope:design, scope:ui, type:fix, priority:medium

#43 🔨(api): Adding GraphQL Schema
  aerial-mapping/angular.json
  aerial-mapping/apps/aerial-mapping/src/app/app.component.ts
  aerial-mapping/apps/api/src/app/app.module.ts
  aerial-mapping/apps/api/src/app/index.ts
  aerial-mapping/apps/api/src/app/schema.graphql
  aerial-mapping/apps/api/tsconfig.app.json
  aerial-mapping/libs/api/shared/services/prisma/data-access/.babelrc
  aerial-mapping/libs/api/shared/services/prisma/data-access/.eslintrc.json
  aerial-mapping/libs/api/shared/services/prisma/data-access/README.md
  aerial-mapping/libs/api/shared/services/prisma/data-access/jest.config.js
  aerial-mapping/libs/api/shared/services/prisma/data-access/project.json
  aerial-mapping/libs/api/shared/services/prisma/data-access/src/index.ts
  aerial-mapping/libs/api/shared/services/prisma/data-access/src/lib/ApiPrismaService.service.ts
  aerial-mapping/libs/api/shared/services/prisma/data-access/tsconfig.json
  aerial-mapping/libs/api/shared/services/prisma/data-access/tsconfig.lib.json
  aerial-mapping/libs/api/shared/services/prisma/data-access/tsconfig.spec.json
  aerial-mapping/libs/api/shell/feature/src/index.ts
  aerial-mapping/libs/api/shell/feature/src/lib/api-shell-feature.module.ts
  aerial-mapping/libs/api/shell/feature/src/lib/context.ts
  aerial-mapping/libs/api/shell/feature/src/lib/dashboard-repository.module.ts
  aerial-mapping/libs/api/shell/feature/src/lib/dashboard-repository.ts
  aerial-mapping/libs/api/shell/feature/src/lib/dashboard.resolver.ts
  aerial-mapping/libs/api/shell/feature/src/lib/schema.graphql
  aerial-mapping/libs/api/shell/feature/tsconfig.lib.json
  aerial-mapping/package.json
  aerial-mapping/prisma/migrations/20220511140117_/migration.sql
  aerial-mapping/prisma/migrations/20220511221404_/migration.sql
  aerial-mapping/prisma/migrations/20220512104903_/migration.sql
  aerial-mapping/prisma/schema.prisma
  aerial-mapping/tsconfig.base.json
  aerial-mapping/yarn.lock
Labels: enhancement, scope:api, type:feature, priority:high

#44 ✨(ui): Map collections basic formatting
  aerial-mapping/libs/client/mapcollection/src/lib/client-mapcollection.module.spec.ts
  aerial-mapping/libs/client/mapcollection/src/lib/client-mapcollection.module.ts
  aerial-mapping/libs/client/mapcollection/src/lib/mapcollection/mapcollection.component.html
  aerial-mapping/libs/client/mapcollection/src/lib/mapcollection/mapcollection.component.scss
  aerial-mapping/libs/client/mapcollection/src/lib/mapcollection/mapcollection.component.ts
  aerial-mapping/libs/client/register/src/lib/materials/material.module.ts
  aerial-mapping/libs/client/register/src/lib/register/register.component.html
  aerial-mapping/libs/client/register/src/lib/register/register.component.scss
Labels: scope:ui, type:feature, priority:high

#45 🚧(ui): Adding shared front-end API service
  aerial-mapping/apps/aerial-mapping/src/app/app.component.ts
  aerial-mapping/libs/api/shell/feature/src/lib/dashboard-repository.ts
  aerial-mapping/libs/client/shared/services/client-api.service.spec.ts
  aerial-mapping/libs/client/shared/services/client-api.service.ts
  aerial-mapping/package.json
  aerial-mapping/yarn.lock
Labels: scope:api, scope:client, type:refactor, priority:high

#46 💄(ui): Map collections revised formatting
  aerial-mapping/libs/client/mapcollection/src/lib/mapcollection/mapcollection.component.html
  aerial-mapping/libs/client/mapcollection/src/lib/mapcollection/mapcollection.component.scss
Labels: scope:ui, type:feature, priority:high

#49 💄 UI: Finished Dashboard
  aerial-mapping/libs/client/dashboard/src/lib/client-dashboard.module.ts
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.html
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.scss
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.ts
  aerial-mapping/libs/client/shared/components/navbar/src/lib/side-navbar/side-navbar.component.html
Labels: enhancement, scope:client, scope:design, type:feature, priority:high

#51 🚧(api): Connecting front end with api
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.ts
  aerial-mapping/libs/client/shared/services/client-api.service.ts
Labels: scope:api, type:feature, priority:high

#52 💄(ui):Map Collections added new collection button
  aerial-mapping/libs/client/mapcollection/src/lib/mapcollection/mapcollection.component.html
  aerial-mapping/libs/client/mapcollection/src/lib/mapcollection/mapcollection.component.scss
Labels: scope:ui, type:feature, priority:high, priority:medium

#53 ✅ Added Workflows
  .github/workflows/nxtest.yml
Labels: scope:repository, type:test, priority:high

#54 🚧(api): Adding getParks query
  aerial-mapping/angular.json
  aerial-mapping/apps/api/src/app/index.ts
  aerial-mapping/apps/api/src/app/schema.graphql
  aerial-mapping/libs/api/dashboard/feature/src/lib/api/dashboard.resolver.ts
  aerial-mapping/libs/api/dashboard/feature/src/lib/repository/dashboard-repository.ts
  aerial-mapping/libs/api/login/feature/.babelrc
  aerial-mapping/libs/api/login/feature/.eslintrc.json
  aerial-mapping/libs/api/login/feature/README.md
  aerial-mapping/libs/api/login/feature/jest.config.js
  aerial-mapping/libs/api/login/feature/project.json
  aerial-mapping/libs/api/login/feature/src/index.ts
  aerial-mapping/libs/api/login/feature/src/lib/api-login-feature.module.ts
  aerial-mapping/libs/api/login/feature/src/lib/api/login.resolver.ts
  aerial-mapping/libs/api/login/feature/src/lib/repository/login-repository.module.ts
  aerial-mapping/libs/api/login/feature/src/lib/repository/login-repository.ts
  aerial-mapping/libs/api/login/feature/tsconfig.json
  aerial-mapping/libs/api/login/feature/tsconfig.lib.json
  aerial-mapping/libs/api/login/feature/tsconfig.spec.json
  aerial-mapping/libs/api/shell/feature/src/lib/context.ts
  aerial-mapping/tsconfig.base.json
Labels: enhancement, scope:api, scope:repository, priority:medium

#55 :white_check_mark: CICD: Updated workflows
  .github/workflows/full.yml
  .github/workflows/index.yml
  .github/workflows/meta.yml
  .github/workflows/nxtest.yml
Labels: scope:cicd, type:test, priority:high

#56 ✅ CICD: Small Fix
  .github/workflows/full.yml
Labels: scope:cicd, type:fix, priority:high

#63 🚧(ui): Fixing relative and absolute file paths
  aerial-mapping/apps/aerial-mapping/src/app/app-routing.module.ts
  aerial-mapping/apps/aerial-mapping/src/app/app.module.ts
  aerial-mapping/apps/aerial-mapping/src/index.html
  aerial-mapping/apps/aerial-mapping/src/styles.scss
  aerial-mapping/libs/client/dashboard/src/lib/bar-chart/bar-chart.component.ts
  aerial-mapping/libs/client/dashboard/src/lib/bar-chart/bar-chart.module.spec.ts
  aerial-mapping/libs/client/dashboard/src/lib/bar-chart/bar-chart.module.ts
  aerial-mapping/libs/client/dashboard/src/lib/client-dashboard.module.ts
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.spec.ts
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.ts
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.module.spec.ts
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.module.ts
  aerial-mapping/libs/client/file-upload/src/lib/client-file-upload.module.ts
  aerial-mapping/libs/client/image-catalogue/src/lib/client-image-catalogue.module.ts
  aerial-mapping/libs/client/mapcollection/src/lib/client-mapcollection.module.ts
  aerial-mapping/libs/client/mapcollection/src/lib/mapcollection/mapcollection.component.scss
  aerial-mapping/libs/client/shared/assets/src/lib/global.scss
  aerial-mapping/libs/client/shared/services/index.ts
  aerial-mapping/libs/client/shared/services/lib/client-api.module.ts
  aerial-mapping/libs/client/shared/services/lib/client-api.service.spec.ts
  aerial-mapping/libs/client/shared/services/lib/client-api.service.ts
  aerial-mapping/tsconfig.base.json
Labels: scope:cicd, type:fix, priority:high

#58 ✅ CICD: Testing Workflows
  .github/workflows/meta.yml
  .github/workflows/nxtest.yml
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.html
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.ts
Labels: scope:cicd, type:fix, priority:high

#65 ✨(api): Added dashboard data
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.html
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.ts
  aerial-mapping/libs/client/login/src/lib/login/login.component.html
  aerial-mapping/libs/client/login/src/lib/login/login.component.ts
  aerial-mapping/libs/client/shared/services/lib/client-api.service.ts
Labels: scope:api, scope:ui, type:feature, priority:high

#66 💄(ui): Fixed styling issues
  aerial-mapping/libs/client/login/src/lib/login/login.component.html
  aerial-mapping/libs/client/mapcollection/src/lib/mapcollection/mapcollection.component.scss
Labels: scope:ui, type:feature, priority:high

#64 📝 Repo: Added Badges
  README.md
Labels: scope:repository, type:documentation, priority:medium

#67 🎨(api): Altering getAllUsers API query
  aerial-mapping/libs/api/dashboard/feature/src/lib/api/dashboard.resolver.spec.ts
  aerial-mapping/libs/api/dashboard/feature/src/lib/api/dashboard.resolver.ts
  aerial-mapping/libs/api/dashboard/feature/src/lib/repository/dashboard-repository.ts
  aerial-mapping/libs/api/login/feature/src/lib/api/login.resolver.spec.ts
  aerial-mapping/libs/api/shared/services/prisma/data-access/src/index.ts
  aerial-mapping/libs/api/shell/feature/src/lib/api-shell-feature.module.ts
  aerial-mapping/package.json
  aerial-mapping/tsconfig.base.json
  aerial-mapping/yarn.lock
Labels: type:bug, scope:api, priority:high

#69 ✨(ui): Updated dashboard
  aerial-mapping/apps/api/src/app/schema.graphql
  aerial-mapping/libs/api/dashboard/feature/src/lib/api/dashboard.resolver.ts
  aerial-mapping/libs/api/dashboard/feature/src/lib/repository/dashboard-repository.ts
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.html
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.ts
  aerial-mapping/libs/client/shared/services/lib/client-api.service.ts
  aerial-mapping/prisma/migrations/20220512223235_1/migration.sql
  aerial-mapping/prisma/migrations/20220512232703_1/migration.sql
  aerial-mapping/prisma/migrations/20220512233017_1/migration.sql
  aerial-mapping/prisma/schema.prisma
Labels: scope:api, scope:ui, type:feature, priority:high

#68 📝 Repo: Updated Readme
  .github/workflows/index.yml
  .github/workflows/nxtest.yml
  README.md
  aerial-mapping/jest.preset.js
Labels: scope:repository, type:documentation, priority:low

#72 Revert "Revert "✨(ui): Updated dashboard""
  aerial-mapping/apps/api/src/app/schema.graphql
  aerial-mapping/libs/api/dashboard/feature/src/lib/api/dashboard.resolver.ts
  aerial-mapping/libs/api/dashboard/feature/src/lib/repository/dashboard-repository.ts
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.html
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.ts
  aerial-mapping/libs/client/shared/services/lib/client-api.service.ts
  aerial-mapping/prisma/migrations/20220512223235_1/migration.sql
  aerial-mapping/prisma/migrations/20220512232703_1/migration.sql
  aerial-mapping/prisma/migrations/20220512233017_1/migration.sql
  aerial-mapping/prisma/schema.prisma
Labels: type:bug, type:fix, priority:high

#75 ✅(testing): Fixing all tests
  aerial-mapping/apps/aerial-mapping-e2e/src/integration/app.spec.ts
  aerial-mapping/apps/aerial-mapping/src/app/app.component.spec.ts
  aerial-mapping/apps/api/src/app/schema.graphql
  aerial-mapping/jest.preset.js
  aerial-mapping/libs/api/dashboard/feature/src/lib/api/dashboard.resolver.spec.ts
  aerial-mapping/libs/api/dashboard/feature/src/lib/api/dashboard.resolver.ts
  aerial-mapping/libs/api/dashboard/feature/src/lib/repository/dashboard-repository.spec.ts
  aerial-mapping/libs/api/dashboard/feature/src/lib/repository/dashboard-repository.ts
  aerial-mapping/libs/api/login/feature/src/lib/api/login.resolver.spec.ts
  aerial-mapping/libs/api/login/feature/src/lib/api/login.resolver.ts
  aerial-mapping/libs/api/login/feature/src/lib/repository/login-repository.module.ts
  aerial-mapping/libs/client/account/src/lib/account/account.component.spec.ts
  aerial-mapping/libs/client/account/src/lib/account/account.component.ts
  aerial-mapping/libs/client/account/src/lib/client-account.module.spec.ts
  aerial-mapping/libs/client/dashboard/src/lib/bar-chart/bar-chart.module.spec.ts
  aerial-mapping/libs/client/dashboard/src/lib/client-dashboard.module.spec.ts
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.spec.ts
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.module.spec.ts
  aerial-mapping/libs/client/file-upload/src/lib/client-file-upload.module.spec.ts
  aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.spec.ts
  aerial-mapping/libs/client/image-catalogue/src/lib/client-image-catalogue.module.spec.ts
  aerial-mapping/libs/client/image-catalogue/src/lib/image-catalogue/image-catalogue.component.spec.ts
  aerial-mapping/libs/client/login/src/lib/client-login.module.spec.ts
  aerial-mapping/libs/client/login/src/lib/login/login.component.spec.ts
  aerial-mapping/libs/client/mapcollection/src/lib/client-mapcollection.module.spec.ts
  aerial-mapping/libs/client/register/src/lib/client-register.module.spec.ts
  aerial-mapping/libs/client/register/src/lib/register/register.component.spec.ts
  aerial-mapping/libs/client/shared/components/footer/src/lib/client-shared-components-footer.module.spec.ts
  aerial-mapping/libs/client/shared/components/navbar/src/lib/client-shared-components-navbar.module.spec.ts
  aerial-mapping/libs/client/shared/components/navbar/src/lib/client-shared-components-navbar.module.ts
Labels: scope:api, scope:client, scope:repository, type:test, type:fix, priority:low

#76 🚧(api): Adding DateTime scalar to the API
  aerial-mapping/apps/api/src/app/app.module.ts
  aerial-mapping/apps/api/src/app/schema.graphql
  aerial-mapping/apps/api/src/main.ts
  aerial-mapping/libs/api/dashboard/feature/README.md
  aerial-mapping/libs/api/dashboard/feature/src/lib/api/dashboard.resolver.spec.ts
  aerial-mapping/libs/api/dashboard/feature/src/lib/api/dashboard.resolver.ts
  aerial-mapping/libs/api/dashboard/feature/src/lib/repository/dashboard-repository.spec.ts
  aerial-mapping/libs/api/dashboard/feature/src/lib/repository/dashboard-repository.ts
  aerial-mapping/libs/client/dashboard/src/lib/dashboard-view/dashboard-view.component.ts
  aerial-mapping/libs/client/shared/services/lib/client-api.service.ts
Labels: scope:api, type:fix, priority:low

#80 ✨ (api): Added S3 Host uploading functionality
  aerial-mapping/.env
  aerial-mapping/.gitignore
  aerial-mapping/angular.json
  aerial-mapping/apps/api/src/app/schema.graphql
  aerial-mapping/libs/api/s3-upload/api/feature/.babelrc
  aerial-mapping/libs/api/s3-upload/api/feature/.eslintrc.json
  aerial-mapping/libs/api/s3-upload/api/feature/README.md
  aerial-mapping/libs/api/s3-upload/api/feature/jest.config.js
  aerial-mapping/libs/api/s3-upload/api/feature/project.json
  aerial-mapping/libs/api/s3-upload/api/feature/src/index.ts
  aerial-mapping/libs/api/s3-upload/api/feature/src/lib/api-s3-upload-api-feature.module.ts
  aerial-mapping/libs/api/s3-upload/api/feature/src/lib/api-s3-upload-api.resolver.spec.ts
  aerial-mapping/libs/api/s3-upload/api/feature/src/lib/api-s3-upload-api.resolver.ts
  aerial-mapping/libs/api/s3-upload/api/feature/tsconfig.json
  aerial-mapping/libs/api/s3-upload/api/feature/tsconfig.lib.json
  aerial-mapping/libs/api/s3-upload/api/feature/tsconfig.spec.json
  aerial-mapping/libs/api/s3-upload/repository/data-access/.eslintrc.json
  aerial-mapping/libs/api/s3-upload/repository/data-access/README.md
  aerial-mapping/libs/api/s3-upload/repository/data-access/jest.config.js
  aerial-mapping/libs/api/s3-upload/repository/data-access/project.json
  aerial-mapping/libs/api/s3-upload/repository/data-access/src/index.ts
  aerial-mapping/libs/api/s3-upload/repository/data-access/src/lib/api-s3-upload-repository-data-access.module.ts
  aerial-mapping/libs/api/s3-upload/repository/data-access/src/lib/api-s3-upload-repository-data-access.spec.ts
  aerial-mapping/libs/api/s3-upload/repository/data-access/src/lib/api-s3-upload-repository-data-access.ts
  aerial-mapping/libs/api/s3-upload/repository/data-access/tsconfig.json
  aerial-mapping/libs/api/s3-upload/repository/data-access/tsconfig.lib.json
  aerial-mapping/libs/api/s3-upload/repository/data-access/tsconfig.spec.json
  aerial-mapping/libs/api/shell/feature/src/lib/api-shell-feature.module.ts
  aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.html
  aerial-mapping/libs/client/file-upload/src/lib/file-upload/file-upload.component.ts
  aerial-mapping/libs/client/shared/services/package.json
  aerial-mapping/libs/client/shared/services/yarn.lock
  aerial-mapping/package.json
  aerial-mapping/tsconfig.base.json
  aerial-mapping/yarn.lock
  package.json
Labels: enhancement, scope:api, scope:client, scope:db, type:feature, priority:high

#81 ✨(api): Authenticating login with JWT
  aerial-mapping/angular.json
  aerial-mapping/apps/api/src/app/app.module.ts
  aerial-mapping/apps/api/src/app/schema.graphql
  aerial-mapping/libs/api/login/api/feature/README.md
  aerial-mapping/libs/api/login/api/feature/src/lib/api-login-api-feature.module.ts
  aerial-mapping/libs/api/login/api/feature/src/lib/api-login-api.resolver.spec.ts
  aerial-mapping/libs/api/login/api/feature/src/lib/api-login-api.resolver.ts
  aerial-mapping/libs/api/login/api/shared/interfaces/data-access/.eslintrc.json
  aerial-mapping/libs/api/login/api/shared/interfaces/data-access/README.md
  aerial-mapping/libs/api/login/api/shared/interfaces/data-access/jest.config.js
  aerial-mapping/libs/api/login/api/shared/interfaces/data-access/project.json
  aerial-mapping/libs/api/login/api/shared/interfaces/data-access/src/index.ts
  aerial-mapping/libs/api/login/api/shared/interfaces/data-access/src/lib/api-login-api-shared-interfaces-data-access.module.ts
  aerial-mapping/libs/api/login/api/shared/interfaces/data-access/src/lib/api-login-entity.ts
  aerial-mapping/libs/api/login/api/shared/interfaces/data-access/tsconfig.json
  aerial-mapping/libs/api/login/api/shared/interfaces/data-access/tsconfig.lib.json
  aerial-mapping/libs/api/login/api/shared/interfaces/data-access/tsconfig.spec.json
  aerial-mapping/libs/api/login/repository/data-access/src/index.ts
  aerial-mapping/libs/api/login/repository/data-access/src/lib/api-login-repository-data-access.module.ts
  aerial-mapping/libs/api/login/repository/data-access/src/lib/api-login-repository-data-access.spec.ts
  aerial-mapping/libs/api/login/repository/data-access/src/lib/api-login-repository-data-access.ts
  aerial-mapping/libs/api/login/repository/data-access/src/lib/auth/guards/auth.guard.ts
  aerial-mapping/libs/api/shell/feature/src/lib/api-shell-feature.module.ts
  aerial-mapping/package.json
  aerial-mapping/tsconfig.base.json
  aerial-mapping/yarn.lock
Labels: scope:api, type:feature, priority:medium

#83 ✨(api): Adding Register API functionality
  aerial-mapping/angular.json
  aerial-mapping/apps/api/src/app/schema.graphql
  aerial-mapping/libs/api/register/api/feature/.babelrc
  aerial-mapping/libs/api/register/api/feature/.eslintrc.json
  aerial-mapping/libs/api/register/api/feature/README.md
  aerial-mapping/libs/api/register/api/feature/jest.config.js
  aerial-mapping/libs/api/register/api/feature/project.json
  aerial-mapping/libs/api/register/api/feature/src/index.ts
  aerial-mapping/libs/api/register/api/feature/src/lib/api-register-api-feature.module.ts
  aerial-mapping/libs/api/register/api/feature/src/lib/api-register-api.resolver.spec.ts
  aerial-mapping/libs/api/register/api/feature/src/lib/api-register-api.resolver.ts
  aerial-mapping/libs/api/register/api/feature/tsconfig.json
  aerial-mapping/libs/api/register/api/feature/tsconfig.lib.json
  aerial-mapping/libs/api/register/api/feature/tsconfig.spec.json
  aerial-mapping/libs/api/register/repository/data-access/.eslintrc.json
  aerial-mapping/libs/api/register/repository/data-access/README.md
  aerial-mapping/libs/api/register/repository/data-access/jest.config.js
  aerial-mapping/libs/api/register/repository/data-access/project.json
  aerial-mapping/libs/api/register/repository/data-access/src/index.ts
  aerial-mapping/libs/api/register/repository/data-access/src/lib/api-register-repository-data-access.module.ts
  aerial-mapping/libs/api/register/repository/data-access/src/lib/api-register-repository-data-access.spec.ts
  aerial-mapping/libs/api/register/repository/data-access/src/lib/api-register-repository-data-access.ts
  aerial-mapping/libs/api/register/repository/data-access/tsconfig.json
  aerial-mapping/libs/api/register/repository/data-access/tsconfig.lib.json
  aerial-mapping/libs/api/register/repository/data-access/tsconfig.spec.json
  aerial-mapping/libs/api/shell/feature/src/lib/api-shell-feature.module.ts
  aerial-mapping/package.json
  aerial-mapping/prisma/migrations/20220527141824_2/migration.sql
  aerial-mapping/prisma/migrations/20220527142030_2/migration.sql
  aerial-mapping/prisma/schema.prisma
  aerial-mapping/tsconfig.base.json
  aerial-mapping/yarn.lock
Labels: scope:api, scope:db, type:feature, priority:medium

#84 (ui): Accounts Page
  aerial-mapping/libs/client/account/src/lib/account/account.component.html
  aerial-mapping/libs/client/account/src/lib/account/account.component.scss
  aerial-mapping/libs/client/account/src/lib/client-account.module.ts
Labels: scope:ui, type:feature, priority:medium

#85 ✨(ui): Image Catalogue basic layout
  aerial-mapping/libs/client/image-catalogue/src/lib/image-catalogue/image-catalogue.component.html
  aerial-mapping/libs/client/image-catalogue/src/lib/image-catalogue/image-catalogue.component.scss
  aerial-mapping/libs/client/image-catalogue/src/lib/image-catalogue/image-catalogue.component.ts
Labels: scope:ui, type:feature, priority:high

#89 (ui): Accounts page edit pages
  aerial-mapping/libs/client/account/src/lib/account/account.component.html
  aerial-mapping/libs/client/account/src/lib/account/account.component.scss
  aerial-mapping/libs/client/account/src/lib/account/account.component.spec.ts
  aerial-mapping/libs/client/account/src/lib/account/account.component.ts
  aerial-mapping/libs/client/account/src/lib/client-account.module.ts
Labels: scope:ui, type:feature, priority:medium

#93 ✨(ui): Image catalogue UI fixes
  aerial-mapping/libs/client/image-catalogue/src/lib/image-catalogue/image-catalogue.component.html
  aerial-mapping/libs/client/image-catalogue/src/lib/image-catalogue/image-catalogue.component.scss
  aerial-mapping/libs/client/image-catalogue/src/lib/image-catalogue/image-catalogue.component.ts
Labels: scope:ui, type:feature, priority:high
