Repository COS301-SE-2022/Map-out-game-reserves-using-aerial-photographs, pull requests merged in 2022-07, with the labels that each got.

#156 🐛(ui): Fixed Angular Material
  aerial-mapping/angular.json
  aerial-mapping/apps/aerial-mapping-e2e/project.json
  aerial-mapping/apps/aerial-mapping/jest.config.ts
  aerial-mapping/apps/aerial-mapping/project.json
  aerial-mapping/apps/aerial-mapping/src/index.html
  aerial-mapping/apps/aerial-mapping/src/styles.scss
  aerial-mapping/apps/aerial-mapping/tsconfig.app.json
  aerial-mapping/apps/aerial-mapping/tsconfig.json
  aerial-mapping/apps/api/jest.config.ts
  aerial-mapping/jest.config.ts
  aerial-mapping/jest.preset.js
  aerial-mapping/jest.preset.ts
  aerial-mapping/libs/client/account/src/lib/account/account.component.ts
  aerial-mapping/libs/client/account/tsconfig.json
  aerial-mapping/libs/client/dashboard/project.json
  aerial-mapping/libs/client/dashboard/tsconfig.json
  aerial-mapping/libs/client/file-upload/project.json
  aerial-mapping/libs/client/file-upload/tsconfig.json
  aerial-mapping/libs/client/image-catalogue/project.json
  aerial-mapping/libs/client/image-catalogue/src/lib/client-image-catalogue.module.ts
  aerial-mapping/libs/client/image-catalogue/src/lib/image-catalogue/image-catalogue.component.html
  aerial-mapping/libs/client/image-catalogue/src/lib/image-catalogue/image-catalogue.component.scss
  aerial-mapping/libs/client/image-catalogue/src/lib/image-catalogue/image-catalogue.component.spec.ts
  aerial-mapping/libs/client/image-catalogue/src/lib/image-catalogue/image-catalogue.component.ts
  aerial-mapping/libs/client/image-catalogue/tsconfig.json
  aerial-mapping/libs/client/login/project.json
  aerial-mapping/libs/client/login/src/lib/login/login.component.html
  aerial-mapping/libs/client/login/src/lib/login/login.component.scss
  aerial-mapping/libs/client/login/src/lib/login/login.component.spec.ts
  aerial-mapping/libs/client/login/src/lib/login/login.component.ts
  aerial-mapping/libs/client/login/tsconfig.json
  aerial-mapping/libs/client/map/project.json
  aerial-mapping/libs/client/map/tsconfig.json
  aerial-mapping/libs/client/mapcollection/project.json
  aerial-mapping/libs/client/mapcollection/tsconfig.json
  aerial-mapping/libs/client/register/project.json
  aerial-mapping/libs/client/register/src/lib/register/register.component.ts
  aerial-mapping/libs/client/register/tsconfig.json
  aerial-mapping/libs/client/shared/assets/project.json
  aerial-mapping/libs/client/shared/assets/tsconfig.json
  aerial-mapping/libs/client/shared/components/footer/project.json
  aerial-mapping/libs/client/shared/components/footer/tsconfig.json
  aerial-mapping/libs/client/shared/components/navbar/project.json
  aerial-mapping/libs/client/shared/components/navbar/tsconfig.json
  aerial-mapping/migrations.json
  aerial-mapping/nx.json
  aerial-mapping/package.json
  aerial-mapping/tsconfig.base.json
  aerial-mapping/yarn.lock
Labels: scope:ui, type:fix, priority:high

#157 :bug: (fix) - Changed Untyped Forms to Forms
  aerial-mapping/libs/client/account/src/lib/account/account.component.ts
  aerial-mapping/libs/client/register/src/lib/register/register.component.ts
Labels: scope:client, type:fix, priority:high

#160 Adding Components
  angular.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/dashboard/bar-chart/bar-chart.component.html
  src/app/components/dashboard/bar-chart/bar-chart.component.scss
  src/app/components/dashboard/bar-chart/bar-chart.component.spec.ts
  src/app/components/dashboard/bar-chart/bar-chart.component.ts
  src/app/components/dashboard/bar-chart/bar-chart.model.ts
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.component.scss
  src/app/components/dashboard/dashboard.component.spec.ts
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/dashboard/dashboard.module.ts
  src/app/components/login/login.component.html
  src/app/components/login/login.component.scss
  src/app/components/login/login.component.spec.ts
  src/app/components/login/login.component.ts
  src/app/components/login/login.module.ts
  src/app/components/register/register.component.ts
  src/app/components/shared/navbar/navbar.component.html
  src/app/components/shared/navbar/navbar.component.scss
  src/app/components/shared/navbar/navbar.component.spec.ts
  src/app/components/shared/navbar/navbar.component.ts
  src/app/components/shared/navbar/navbar.module.ts
  src/index.html
  src/polyfills.ts
  src/styles.scss
  tsconfig.json
Labels: scope:client, type:feature, priority:high

#161 Adding old pages to new app
  src/app/api/controller/controller.service.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/account/account.component.html
  src/app/components/account/account.component.scss
  src/app/components/account/account.component.spec.ts
  src/app/components/account/account.component.ts
  src/app/components/account/account.module.ts
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.component.scss
  src/app/components/file-upload/file-upload.component.spec.ts
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/file-upload/file-upload.module.ts
  src/app/components/image-catalogue/image-catalogue.component.html
  src/app/components/image-catalogue/image-catalogue.component.scss
  src/app/components/image-catalogue/image-catalogue.component.spec.ts
  src/app/components/image-catalogue/image-catalogue.component.ts
  src/app/components/image-catalogue/image-catalogue.module.ts
  src/app/components/map-collections/map-collections.component.html
  src/app/components/map-collections/map-collections.component.scss
  src/app/components/map-collections/map-collections.component.spec.ts
  src/app/components/map-collections/map-collections.component.ts
  src/app/components/map-collections/map-collections.module.ts
  src/app/components/map/map.component.html
  src/app/components/map/map.component.scss
  src/app/components/map/map.component.spec.ts
  src/app/components/map/map.component.ts
  src/app/components/map/map.module.ts
Labels: scope:client, type:feature, priority:high

#164 Update README.md
  README.md
Labels: scope:repository, type:documentation, priority:low

#186 🚧 (api) : temporary api linking
  src/app/api/controller/controller.service.ts
  src/app/app.module.ts
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/file-upload/file-upload.component.scss
  src/app/components/map/map.component.scss
Labels: scope:api, type:fix, priority:high

#190 🚧(client): Integrating the Account Page
  .graphqlconfig.yml
  amplify/backend/api/amplifyapp/schema.graphql
  package-lock.json
  package.json
  src/app/API.service.ts
  src/app/api/controller/controller.service.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/auth/auth.guard.spec.ts
  src/app/auth/auth.guard.ts
  src/app/components/account/account.component.html
  src/app/components/account/account.component.scss
  src/app/components/account/account.component.ts
  src/app/components/account/account.module.ts
  src/app/components/account/email-dialog/email-dialog.component.html
  src/app/components/account/email-dialog/email-dialog.component.scss
  src/app/components/account/email-dialog/email-dialog.component.spec.ts
  src/app/components/account/email-dialog/email-dialog.component.ts
  src/app/components/account/name-dialog/name-dialog.component.html
  src/app/components/account/name-dialog/name-dialog.component.scss
  src/app/components/account/name-dialog/name-dialog.component.spec.ts
  src/app/components/account/name-dialog/name-dialog.component.ts
  src/app/components/account/password-dialog/password-dialog.component.html
  src/app/components/account/password-dialog/password-dialog.component.scss
  src/app/components/account/password-dialog/password-dialog.component.spec.ts
  src/app/components/account/password-dialog/password-dialog.component.ts
  src/app/components/account/register-link-dialog/register-link-dialog.component.html
  src/app/components/account/register-link-dialog/register-link-dialog.component.scss
  src/app/components/account/register-link-dialog/register-link-dialog.component.spec.ts
  src/app/components/account/register-link-dialog/register-link-dialog.component.ts
  src/app/components/dashboard/bar-chart/bar-chart.component.html
  src/app/components/login/login.component.ts
  src/app/components/shared/navbar/navbar.component.html
  src/graphql/mutations.graphql
  src/graphql/queries.graphql
  src/graphql/schema.json
  src/graphql/subscriptions.graphql
  src/index.html
  src/models/schema.js
  src/styles.scss
Labels: scope:client, type:feature, priority:high

#192 🚧(client): Integrating Image Catalogues Page
  amplify/backend/api/amplifyapp/schema.graphql
  amplify/backend/backend-config.json
  amplify/backend/function/registerlinkemailer/amplify.state
  amplify/backend/function/registerlinkemailer/custom-policies.json
  amplify/backend/function/registerlinkemailer/function-parameters.json
  amplify/backend/function/registerlinkemailer/registerlinkemailer-cloudformation-template.json
  amplify/backend/function/registerlinkemailer/src/event.json
  amplify/backend/function/registerlinkemailer/src/index.js
  amplify/backend/function/registerlinkemailer/src/package.json
  amplify/backend/function/registerlinkemailer/src/yarn.lock
  amplify/backend/types/amplify-dependent-resources-ref.d.ts
  amplify/team-provider-info.json
  angular.json
  src/app/API.service.ts
  src/app/api/controller/controller.service.ts
  src/app/app.module.ts
  src/app/components/account/account.component.html
  src/app/components/account/account.component.scss
  src/app/components/account/account.component.ts
  src/app/components/account/account.module.ts
  src/app/components/account/register-link-dialog/register-link-dialog.component.html
  src/app/components/account/register-link-dialog/register-link-dialog.component.ts
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.component.scss
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/dashboard/dashboard.module.ts
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.component.scss
  src/app/components/image-catalogue/image-catalogue.component.html
  src/app/components/image-catalogue/image-catalogue.component.scss
  src/app/components/image-catalogue/image-catalogue.component.ts
  src/app/components/image-catalogue/image-catalogue.module.ts
  src/app/components/map-collections/map-collections.component.html
  src/app/components/map-collections/map-collections.component.scss
  src/app/components/map-collections/map-collections.module.ts
  src/app/components/register/otp-dialog/otp-dialog.component.html
  src/app/components/register/otp-dialog/otp-dialog.component.scss
  src/app/components/register/otp-dialog/otp-dialog.component.spec.ts
  src/app/components/register/otp-dialog/otp-dialog.component.ts
  src/app/components/register/register.component.html
  src/app/components/register/register.component.scss
  src/app/components/register/register.component.ts
  src/app/components/register/register.module.ts
  src/app/components/shared/navbar/navbar.component.html
  src/app/components/shared/navbar/navbar.component.scss
  src/graphql/mutations.graphql
  src/graphql/queries.graphql
  src/graphql/schema.json
  src/graphql/subscriptions.graphql
  src/models/index.d.ts
  src/models/schema.js
  src/styles.scss
Labels: scope:client, type:feature, priority:high

#193 🚧(db): Integrated new S3 bucket
  src/app/api/controller/controller.service.ts
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/image-catalogue/image-catalogue.component.ts
Labels: scope:db, type:feature, priority:high

#194 Adjusting Config for Production Build
  amplify/backend/api/amplifyapp/schema.graphql
  amplify/backend/backend-config.json
  amplify/backend/function/S3Triggerbfbfb03a/amplify.state
  amplify/backend/function/registerlinkemailer/registerlinkemailer-cloudformation-template.json
  amplify/backend/function/registerlinkemailer/src/index.js
  amplify/backend/types/amplify-dependent-resources-ref.d.ts
  amplify/team-provider-info.json
  angular.json
  src/app/API.service.ts
  src/app/api/controller/controller.service.ts
  src/app/components/account/account.component.ts
  src/graphql/queries.graphql
  src/graphql/schema.json
  src/models/schema.js
Labels: scope:client, type:feature, priority:medium

#195 🚧(db): Added folders(S3) and thumbnails
  src/app/api/controller/controller.service.ts
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/image-catalogue/image-catalogue.component.ts
Labels: scope:db, type:feature, priority:high

#163 CICD: Fixing yaml files
  .github/workflows/nxtest.yml
  amplify/hooks/README.md
  src/app/components/file-upload/file-upload.component.scss
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/map/map.component.scss
Labels: scope:cicd, type:fix, priority:high

#197 🐛(ui): Fixed image loading on image catalogue page
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/image-catalogue/image-catalogue.component.html
  src/app/components/image-catalogue/image-catalogue.component.ts
Labels: type:bug, scope:ui, type:fix, priority:high

#199 CICD: Fix codecov and Yaml
  .github/workflows/full.yml
  .github/workflows/index.yml
  .github/workflows/nxtest.yml
  .github/workflows/tests.yml
  karma.conf.js
Labels: scope:cicd, type:test, type:fix, priority:high

#196 ✨(Testing): Re-integrating e2e tests and unit tests
  .gitignore
  README.md
  amplify/backend/api/amplifyapp/cli-inputs.json
  amplify/backend/api/amplifyapp/parameters.json
  amplify/backend/api/amplifyapp/schema.graphql
  amplify/backend/backend-config.json
  amplify/team-provider-info.json
  angular.json
  cypress.config.ts
  cypress/e2e/app.po.ts
  cypress/e2e/spec.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/tsconfig.json
  package-lock.json
  package.json
  src/app/api/controller/controller.service.spec.ts
  src/app/api/controller/controller.service.ts
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/auth/auth.guard.spec.ts
  src/app/components/account/account.component.html
  src/app/components/account/account.component.spec.ts
  src/app/components/account/email-dialog/email-dialog.component.spec.ts
  src/app/components/account/name-dialog/name-dialog.component.spec.ts
  src/app/components/account/password-dialog/password-dialog.component.spec.ts
  src/app/components/account/password-dialog/password-dialog.component.ts
  src/app/components/account/register-link-dialog/register-link-dialog.component.spec.ts
  src/app/components/dashboard/dashboard.component.spec.ts
  src/app/components/dashboard/dashboard.module.ts
  src/app/components/file-upload/file-upload.component.spec.ts
  src/app/components/file-upload/file-upload.module.ts
  src/app/components/image-catalogue/image-catalogue.component.spec.ts
  src/app/components/login/login.component.spec.ts
  src/app/components/login/login.component.ts
  src/app/components/register/otp-dialog/otp-dialog.component.spec.ts
  src/app/components/register/register.component.spec.ts
  src/app/components/register/register.component.ts
  src/app/components/register/register.module.ts
  src/app/components/shared/navbar/navbar.component.html
  src/models/schema.js
  tsconfig.app.json
  tsconfig.json
Labels: scope:cicd, scope:client, type:feature, priority:medium

#200 CICD: Fixing codecov
  karma.conf.js
Labels: scope:cicd, type:test, type:fix, priority:high

#201 💄 (ui): UI NavBar restyle
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/account/account.component.html
  src/app/components/account/account.component.scss
  src/app/components/account/account.module.ts
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.component.scss
  src/app/components/file-upload/file-upload.component.html
  src/app/components/image-catalogue/image-catalogue.component.html
  src/app/components/map-collections/map-collections.component.html
  src/app/components/map-collections/map-collections.component.scss
  src/app/components/shared/navbar/navbar.component.html
  src/app/components/shared/navbar/navbar.component.scss
  src/app/components/shared/navbar/navbar.component.ts
  src/app/components/shared/navbar/navbar.module.ts
  src/styles.scss
Labels: scope:ui, type:refactor, priority:high

#203 💄(ui): Adding the footer to all the pages
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/account/account.component.html
  src/app/components/account/account.module.ts
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.module.ts
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.module.ts
  src/app/components/image-catalogue/image-catalogue.component.html
  src/app/components/image-catalogue/image-catalogue.module.ts
  src/app/components/login/login.component.html
  src/app/components/login/login.module.ts
  src/app/components/register/register.component.html
  src/app/components/register/register.module.ts
  src/app/components/shared/footer/footer.component.html
  src/app/components/shared/footer/footer.component.scss
  src/app/components/shared/footer/footer.component.spec.ts
  src/app/components/shared/footer/footer.component.ts
  src/app/components/shared/footer/footer.module.ts
Labels: scope:ui, type:refactor, priority:high

#206 ✨(ui): Added image resizing and fixed thumbnails
  package-lock.json
  package.json
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.component.ts
Labels: scope:ui, type:feature, priority:high

#205 💄(ui): Dashboard UI update
  src/app/app-routing.module.ts
  src/app/components/account/account.component.html
  src/app/components/account/account.component.scss
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.component.scss
  src/app/components/image-catalogue/image-catalogue.component.scss
  src/app/components/shared/navbar/navbar.component.html
  src/app/components/shared/navbar/navbar.component.scss
  src/app/components/shared/navbar/navbar.component.ts
  src/styles.scss
Labels: scope:ui, type:refactor, priority:high

#207 💄(ui): Update of the file upload page
  package-lock.json
  src/app/components/dashboard/dashboard.component.scss
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.component.scss
  src/app/components/file-upload/file-upload.module.ts
  src/styles.scss
Labels: scope:ui, type:refactor, priority:high

#208 💄 (ui): Navbar mobile size update
  src/app/components/account/account.component.html
  src/app/components/account/account.component.scss
  src/app/components/dashboard/bar-chart/bar-chart.component.ts
  src/app/components/dashboard/dashboard.component.scss
  src/app/components/image-catalogue/image-catalogue.component.html
  src/app/components/image-catalogue/image-catalogue.module.ts
  src/app/components/shared/navbar/navbar.component.scss
  src/styles.scss
Labels: scope:ui, type:refactor, priority:high

#210 ✨(db): Added image upload feature
  amplify/backend/api/amplifyapp/schema.graphql
  package.json
  src/app/API.service.ts
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/image-catalogue/image-catalogue.component.html
  src/app/components/image-catalogue/image-catalogue.component.ts
  src/graphql/mutations.graphql
  src/graphql/queries.graphql
  src/graphql/schema.json
  src/graphql/subscriptions.graphql
  src/models/schema.js
Labels: scope:repository, type:feature, priority:high

#213 🚧(client): Integrating WebODM
  .gitignore
  amplify/backend/api/amplifyapp/schema.graphql
  amplify/backend/function/registerlinkemailer/registerlinkemailer-cloudformation-template.json
  amplify/backend/types/amplify-dependent-resources-ref.d.ts
  package.json
  src/app/API.service.ts
  src/app/api/controller/controller.service.ts
  src/app/app.component.ts
  src/app/components/account/account.component.ts
  src/app/components/dashboard/bar-chart/bar-chart.component.ts
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/image-catalogue/image-catalogue.component.html
  src/app/components/image-catalogue/image-catalogue.component.ts
  src/app/components/login/login.component.ts
  src/app/components/register/register.component.ts
  src/graphql/mutations.graphql
  src/graphql/queries.graphql
  src/graphql/schema.json
  src/graphql/subscriptions.graphql
  src/models/index.d.ts
  src/models/schema.js
Labels: scope:client, type:feature, priority:high

#214 Adding functionality to file upload ui
  package-lock.json
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.component.scss
  src/app/components/file-upload/file-upload.component.ts
Labels: scope:ui, type:fix, priority:medium

#216 💄 (ui): Map catalogue UI update
  src/app/app-routing.module.ts
  src/app/components/account/account.component.scss
  src/app/components/image-catalogue/image-catalogue.component.html
  src/app/components/image-catalogue/image-catalogue.component.scss
  src/app/components/image-catalogue/image-catalogue.component.ts
  src/app/components/image-catalogue/image-catalogue.module.ts
  src/app/components/image-catalogue/image-dialog/image-dialog.component.html
  src/app/components/image-catalogue/image-dialog/image-dialog.component.scss
  src/app/components/image-catalogue/image-dialog/image-dialog.component.spec.ts
  src/app/components/image-catalogue/image-dialog/image-dialog.component.ts
  src/app/components/shared/navbar/navbar.component.html
  src/assets/icons8-drone-16.png
  src/index.html
Labels: scope:ui, type:refactor, priority:high

#218 ✨(client): integrated resolution changing
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.component.ts
Labels: scope:api, scope:client, type:feature, priority:high

#219 💄 (ui): Upload progress bar
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.component.scss
  src/app/components/file-upload/file-upload.component.ts
Labels: scope:ui, type:refactor, type:fix, priority:high

#220 Update README.md
  README.md
Labels: scope:repository, type:documentation, priority:low

#221 Update README.md
  README.md
Labels: scope:repository, type:documentation, priority:low

#222 🚧(client): Integrating WebODM
  amplify/backend/api/amplifyapp/schema.graphql
  src/app/API.service.ts
  src/app/api/controller/controller.service.ts
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/register/register.component.ts
  src/graphql/schema.json
  src/models/index.d.ts
  src/models/schema.js
Labels: scope:client, type:feature, priority:high

#225 Update README.md
  README.md
Labels: scope:repository, type:fix, priority:low

#224 ✅(testing) Fixing API.service.ts
  src/app/api/controller/controller.service.spec.ts
  src/app/app.module.ts
  src/app/components/image-catalogue/image-catalogue.module.ts
  src/app/components/register/register.component.spec.ts
Labels: scope:api, scope:client, type:fix, priority:high

#226 Rename API.service.ts to api.service.ts
  src/app/api.service.ts
Labels: scope:cicd, type:fix, priority:high

#232 Hotfix
  amplify/backend/api/amplifyapp/schema.graphql
  src/app/API.service.ts
  src/app/api/controller/controller.service.spec.ts
  src/app/app.module.ts
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/image-catalogue/image-catalogue.module.ts
  src/app/components/register/register.component.spec.ts
  src/graphql/schema.json
  src/models/index.d.ts
  src/models/schema.js
Labels: type:bug, scope:client, priority:high

#233 🚧(client): Dashboard bug fix
  .graphqlconfig.yml
  amplify/backend/api/amplifyapp/schema.graphql
  cypress/e2e/app.po.ts
  cypress/e2e/spec.cy.ts
  src/app/API.service.ts
  src/app/api/controller/controller.service.spec.ts
  src/app/api/controller/controller.service.ts
  src/app/app.module.ts
  src/app/components/account/account.component.ts
  src/app/components/dashboard/bar-chart/bar-chart.component.ts
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/dashboard/dashboard.module.ts
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/image-catalogue/image-catalogue.component.spec.ts
  src/app/components/image-catalogue/image-catalogue.component.ts
  src/app/components/image-catalogue/image-dialog/image-dialog.component.spec.ts
  src/app/components/login/login.module.ts
  src/app/components/map/map.module.ts
  src/app/components/register/register.component.spec.ts
  src/app/components/register/register.component.ts
  src/graphql/schema.json
  src/models/index.d.ts
  src/models/schema.js
Labels: scope:client, type:fix, priority:high

#235 ✅(testing): Added automated integration and more unit testing
  .github/workflows/integration.yml
  .graphqlconfig.yml
  cypress.config.ts
  cypress/e2e/app.po.ts
  cypress/e2e/spec.cy.ts
  package-lock.json
  package.json
  src/app/api/controller/controller.service.spec.ts
  src/app/api/controller/controller.service.ts
  src/app/app.module.ts
  src/app/components/account/account.component.ts
  src/app/components/dashboard/bar-chart/bar-chart.component.ts
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/dashboard/dashboard.module.ts
  src/app/components/file-upload/file-upload.component.html
  src/app/components/file-upload/file-upload.component.spec.ts
  src/app/components/file-upload/file-upload.component.ts
  src/app/components/image-catalogue/image-catalogue.component.html
  src/app/components/image-catalogue/image-catalogue.component.spec.ts
  src/app/components/image-catalogue/image-catalogue.component.ts
  src/app/components/image-catalogue/image-dialog/image-dialog.component.spec.ts
  src/app/components/login/login.module.ts
  src/app/components/map/map.module.ts
  src/app/components/register/register.component.spec.ts
  src/app/components/register/register.component.ts
  src/graphql/schema.json
Labels: scope:cicd, type:feature, type:fix, priority:high
